# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /direct-debit-consents/{consentId}_get for http method type GET 
# RoostTestHash=296226bc11
# 
# 

# ********RoostGPT********
Feature: Real-time Direct Debit Consent Setup

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Retrieve direct-debit consent resource with valid consentId
    Given path '/direct-debit-consents/', <consentId>
    And header Authorization = 'Bearer ' + authToken
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = 'unique-interaction-id'
    And header Accept-Language = 'en-HK'
    When method GET
    Then status 200
    And assert response.headers['x-fapi-interaction-id'] != null
    And match response == """{
      data: '#object',
      links: '#object'
    }"""
    And match response.data == """{
      consentId: '#string',
      creationDate: '#string',
      status: '#string',
      statusUpdateDate: '#string',
      permissions: '#array'
    }"""
    And match response.links == """{
      self: '#string'
    }"""

    Examples:
      | consentId                              |
      | '7404e99b-1a4d-4b08-b441-c327661527f0' |

  Scenario: Retrieve direct-debit consent resource with invalid consentId
    Given path '/direct-debit-consents/invalid-consent-id'
    And header Authorization = 'Bearer ' + authToken
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = 'unique-interaction-id'
    And header Accept-Language = 'en-HK'
    When method GET
    Then status 400
    And assert response.headers['x-fapi-interaction-id'] != null
    And match response == """{
      errors: '#array'
    }"""

  Scenario: Retrieve direct-debit consent resource without Authorization header
    Given path '/direct-debit-consents/7404e99b-1a4d-4b08-b441-c327661527f0'
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = 'unique-interaction-id'
    And header Accept-Language = 'en-HK'
    When method GET
    Then status 401
    And assert response.headers['x-fapi-interaction-id'] != null
