# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /instructions_post for http method type POST 
# RoostTestHash=68a776c788
# 
# 

# ********RoostGPT********
Feature: Direct Debit Instructions Fulfilment

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def headersWithAuth = { Authorization: 'Bearer ' + authToken }

Scenario Outline: Successful Direct Debit Instructions Creation
    Given path '/instructions'
    And request 
    """
    <requestBody>
    """
    And headers headersWithAuth
    And header x-idempotency-key = <xIdempotencyKey>
    When method post
    Then status 201
    And match response.paymentInformationStatus == #['ACSC', 'RJCT', 'ACCP', 'ACSP']
    And match response.processResult.responseCode == #['00', '99']
    And match response.transactionIdentification != null

Examples:
    | requestBody                                                                                                                       | xIdempotencyKey |
    | { "merchantInstructionIdentification": "123456", "creditorAccount": { "bankCode": "001", "accountIdentification": "987654321", "currency": "USD" }, "instructedAmount": "100.00", "instructedAmountCurrency": "USD" }                      | 'abc-12345678'  |
    | { "merchantInstructionIdentification": "123457", "mandateIdentification": "98765", "debtorName": "John Doe", "debtorAccount": { "bankCode": "002", "accountIdentification": "123456789", "currency": "EUR" }, "instructedAmount": "200.00", "instructedAmountCurrency": "EUR" } | 'def-87654321'  |

Scenario Outline: Direct Debit Instructions Creation With Invalid Amount
    Given path '/instructions'
    And request 
    """
    <requestBody>
    """
    And headers headersWithAuth
    And header x-idempotency-key = <xIdempotencyKey>
    When method post
    Then status 400
    And match response.errors[0].code == 'OB.Field.Invalid'

Examples:
    | requestBody                                                                                                          | xIdempotencyKey |
    | { "merchantInstructionIdentification": "123458", "instructedAmount": "invalid", "instructedAmountCurrency": "HKD" } | 'ghi-12345678'  |

Scenario Outline: Direct Debit Instructions Creation Without Authorization
    Given path '/instructions'
    And request 
    """
    <requestBody>
    """
    And header x-idempotency-key = <xIdempotencyKey>
    When method post
    Then status 401

Examples:
    | requestBody                                                                                                                       | xIdempotencyKey |
    | { "merchantInstructionIdentification": "123459", "creditorAccount": { "bankCode": "003", "accountIdentification": "123456789", "currency": "GBP" }, "instructedAmount": "300.00", "instructedAmountCurrency": "GBP" }                      | 'jkl-12345678'  |
