# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=adfce3f1d2
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Information Retrieval

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Get information about a specific Nobel Prize by category and year
  Given path '2.1/nobelPrize', '<category>', '<year>'
  And header Authorization = 'Bearer ' + authToken
  When method get
  Then status 200
  And assert response contains { nobelPrize: '#object' }
  And match response.nobelPrize == { awardYear: '#number', category: '#object', categoryFullName: '#object', dateAwarded: '#string', prizeAmount: '#number', prizeAmountAdjusted: '#number', topMotivation: '#object', laureates: '#array' }
  And match each response.nobelPrize.laureates[*].id == '#number'
  And match each response.nobelPrize.laureates[*].portion == '#string?'
  And match each response.nobelPrize.laureates[*].sortOrder == '#string?'

  Examples:
    | category | year |
    | 'che'    | 2000 |
    | 'eco'    | 2001 |
    | 'lit'    | 2002 |
    | 'pea'    | 2003 |
    | 'phy'    | 2004 |
    | 'med'    | 2005 |

Scenario: Attempt to get Nobel Prize information with invalid category
  Given path '2.1/nobelPrize', 'invalid', '2000'
  And header Authorization = 'Bearer ' + authToken
  When method get
  Then status 400
  And match response == { code: '404', message: 'There is not Laureate born that date' }

Scenario: Attempt to get Nobel Prize information with future year
  Given path '2.1/nobelPrize', 'che', 3000
  And header Authorization = 'Bearer ' + authToken
  When method get
  Then status 404
  And match response == { code: '404', message: 'There is not Laureate born that date' }

Scenario: Attempt to get Nobel Prize information with year below minimum
  Given path '2.1/nobelPrize', 'che', 1800
  And header Authorization = 'Bearer ' + authToken
  When method get
  Then status 422
  And match response == { code: '404', message: 'There is not Laureate born that date' }
