# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /reports_post for http method type POST 
# RoostTestHash=66b519ad26
# 
# 

# ********RoostGPT********
Feature: Fulfilment endpoints - Reports API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authHeader = karate.properties['AUTH_TOKEN']

Scenario Outline: Create a new report with valid data
  Given path '/reports'
  And header Authorization = 'Bearer ' + authHeader
  And header x-idempotency-key = '<x-idempotency-key>'
  And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
  And header x-fapi-auth-date = '<x-fapi-auth-date>'
  And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
  And request 
  """
  <requestBody>
  """
  When method post
  Then status 201
  And match response.processResult.responseCode == '00'

  Examples:
    | x-idempotency-key | x-fapi-customer-ip-address | x-fapi-auth-date               | x-fapi-interaction-id | requestBody                                                                                                                                                         |
    | 'IdempKey12345'   | '192.168.1.1'              | 'Sun, 10 Sep 2017 19:43:31 UTC' | 'UUID-12345'          | { "creditorAccount": { "bankCode": "123", "accountIdentification": "ABC123456", "currency": "USD" }, "reportType": "DDAReport", "reportingDate": "2023-01-01" } |

Scenario Outline: Create a new report with invalid data - missing required fields
  Given path '/reports'
  And header Authorization = 'Bearer ' + authHeader
  And header x-idempotency-key = '<x-idempotency-key>'
  And request 
  """
  <requestBody>
  """
  When method post
  Then status 400
  And match response.errors[*].code contains 'OB.Field.Missing'

  Examples:
    | x-idempotency-key | requestBody                  |
    | 'IdempKey67890'   | { "reportType": "DDIReport" }|

Scenario: Unauthorized access attempt
  Given path '/reports'
  And header Authorization = 'Bearer invalid_token'
  And request 
  """
  { "creditorAccount": { "bankCode": "123", "accountIdentification": "ABC123456", "currency": "USD" }, "reportType": "DDIReport", "reportingDate": "2023-01-01" }
  """
  When method post
  Then status 401

Scenario: Forbidden access attempt
  Given path '/reports'
  And header Authorization = 'Bearer ' + authHeader
  And header x-fapi-interaction-id = 'UUID-67890'
  And request 
  """
  { "creditorAccount": { "bankCode": "789", "accountIdentification": "XYZ789012", "currency": "EUR" }, "reportType": "DDIReport", "reportingDate": "2023-01-01" }
  """
  When method post
  Then status 403
