// ********RoostGPT********
/*
Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview

Test generated for /laureates_get for http method type GET in rest-assured framework

RoostTestHash=bb9ad621b1


*/

// ********RoostGPT********
package com.baeldung.RoostTest;
import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import org.json.JSONArray;

public class laureatesGetTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      String[] envVarsList = {""};
      envList = dataloader.load("src\test\java\com\baeldung\RoostTest\laureatesGetTest.csv", envVarsList);
    }

  
    @Test  
    public void laureatesGet_Test() {
        this.setUp();
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty()) ? testData.get("BASE_URL"): "http://api.nobelprize.org/2.1";  
  
                Response responseObj = given()
				.queryParam("offset", testData.get("offset") != null ? testData.get("offset") : "")
				.queryParam("limit", testData.get("limit") != null ? testData.get("limit") : "")
				.queryParam("sort", testData.get("sort") != null ? testData.get("sort") : "")
				.queryParam("ID", testData.get("ID") != null ? testData.get("ID") : "")
				.queryParam("name", testData.get("name") != null ? testData.get("name") : "")
				.queryParam("gender", testData.get("gender") != null ? testData.get("gender") : "")
				.queryParam("motivation", testData.get("motivation") != null ? testData.get("motivation") : "")
				.queryParam("affiliation", testData.get("affiliation") != null ? testData.get("affiliation") : "")
				.queryParam("residence", testData.get("residence") != null ? testData.get("residence") : "")
				.queryParam("birthDate", testData.get("birthDate") != null ? testData.get("birthDate") : "")
				.queryParam("birthDateTo", testData.get("birthDateTo") != null ? testData.get("birthDateTo") : "")
				.queryParam("deathDate", testData.get("deathDate") != null ? testData.get("deathDate") : "")
				.queryParam("deathDateTo", testData.get("deathDateTo") != null ? testData.get("deathDateTo") : "")
				.queryParam("foundedDate", testData.get("foundedDate") != null ? testData.get("foundedDate") : "")
				.queryParam("birthCity", testData.get("birthCity") != null ? testData.get("birthCity") : "")
				.queryParam("birthCountry", testData.get("birthCountry") != null ? testData.get("birthCountry") : "")
				.queryParam("birthContinent", testData.get("birthContinent") != null ? testData.get("birthContinent") : "")
				.queryParam("deathCity", testData.get("deathCity") != null ? testData.get("deathCity") : "")
				.queryParam("deathCountry", testData.get("deathCountry") != null ? testData.get("deathCountry") : "")
				.queryParam("deathContinent", testData.get("deathContinent") != null ? testData.get("deathContinent") : "")
				.queryParam("foundedCity", testData.get("foundedCity") != null ? testData.get("foundedCity") : "")
				.queryParam("foundedCountry", testData.get("foundedCountry") != null ? testData.get("foundedCountry") : "")
				.queryParam("foundedContinent", testData.get("foundedContinent") != null ? testData.get("foundedContinent") : "")
				.queryParam("HeadquartersCity", testData.get("HeadquartersCity") != null ? testData.get("HeadquartersCity") : "")
				.queryParam("HeadquartersCountry", testData.get("HeadquartersCountry") != null ? testData.get("HeadquartersCountry") : "")
				.queryParam("HeadquartersContinent", testData.get("HeadquartersContinent") != null ? testData.get("HeadquartersContinent") : "")
				.queryParam("nobelPrizeYear", testData.get("nobelPrizeYear") != null ? testData.get("nobelPrizeYear") : "")
				.queryParam("yearTo", testData.get("yearTo") != null ? testData.get("yearTo") : "")
				.queryParam("nobelPrizeCategory", testData.get("nobelPrizeCategory") != null ? testData.get("nobelPrizeCategory") : "")
				.queryParam("format", testData.get("format") != null ? testData.get("format") : "")
				.queryParam("csvLang", testData.get("csvLang") != null ? testData.get("csvLang") : "")
                .when()
                .get("/laureates")  
                .then() 
                .extract().response(); 
              JsonPath response;
              String contentType = responseObj.getContentType();
              if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
                String xmlResponse = responseObj.asString();
                JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
                JSONObject jsonData = jsonResponse.getJSONObject("xml");
                String jsonString = jsonData.toString();
                response = new JsonPath(jsonString);
        
              } else {  
                response = responseObj.jsonPath(); 
              }  
         
                if (responseObj.statusCode() == 200) {
					System.out.println("Description: Successful call of Laureate(s).");
      
              if (response.get("laureates") != null) {        
                  for (int i = 0; i < response.getList("laureates").size(); i++) {      
              if (response.get("laureates["+ i +"].id") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].id"), instanceOf(Integer.class));  
                MatcherAssert.assertThat(response.getDouble("laureates["+ i +"].id"), greaterThanOrEqualTo(1));
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.knownName") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.knownName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.knownName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.knownName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.knownName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.knownName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.knownName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.givenName") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.givenName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.givenName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.givenName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.givenName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.givenName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.givenName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.familyName") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.familyName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.familyName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.familyName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.familyName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.familyName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.familyName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.fullName") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.fullName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.fullName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.fullName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.fullName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.fullName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.fullName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.filename") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.filename"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.penname") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.penname"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.gender") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.gender"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("laureates["+ i +"].laureateIfPerson.gender"), anyOf(equalTo("female"), equalTo("male")));
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.date") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.date"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.city") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.country") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.cityNow") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.cityNow.sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].laureateIfPerson.birth.place.cityNow.sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].laureateIfPerson.birth.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.countryNow") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.countryNow.sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].laureateIfPerson.birth.place.countryNow.sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].laureateIfPerson.birth.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.continent") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.continent.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.continent.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.continent.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.continent.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.continent.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.continent.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.locationString") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.birth.place.locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.birth.place.locationString.false"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.date") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.date"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.city") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.country") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.cityNow") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.cityNow.sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].laureateIfPerson.death.place.cityNow.sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].laureateIfPerson.death.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.countryNow") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.countryNow.sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].laureateIfPerson.death.place.countryNow.sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].laureateIfPerson.death.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.continent") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.continent.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.continent.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.continent.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.continent.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.continent.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.continent.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.locationString") != null) {      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfPerson.death.place.locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfPerson.death.place.locationString.false"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.orgName") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.orgName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.orgName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.orgName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.orgName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.orgName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.orgName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.nativeName") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.nativeName"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.acronym") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.acronym"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.date") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.date"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.city") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.country") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.cityNow") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.cityNow.sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].laureateIfOrg.founded.place.cityNow.sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].laureateIfOrg.founded.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.countryNow") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.countryNow.sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].laureateIfOrg.founded.place.countryNow.sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].laureateIfOrg.founded.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.continent") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.continent.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.continent.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.continent.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.continent.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.continent.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.continent.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.locationString") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.founded.place.locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.founded.place.locationString.false"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.date") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.date"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.city") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.country") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.cityNow") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.cityNow.sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].laureateIfOrg.dissolution.place.cityNow.sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].laureateIfOrg.dissolution.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.countryNow") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.countryNow.sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].laureateIfOrg.dissolution.place.countryNow.sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].laureateIfOrg.dissolution.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.continent") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.continent.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.continent.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.continent.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.continent.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.continent.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.continent.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.locationString") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.dissolution.place.locationString.false"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.city") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.country") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.cityNow") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.cityNow.sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].laureateIfOrg.headquarters.cityNow.sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].laureateIfOrg.headquarters.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.countryNow") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.countryNow.sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].laureateIfOrg.headquarters.countryNow.sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].laureateIfOrg.headquarters.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.continent") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.continent.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.continent.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.continent.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.continent.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.continent.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.continent.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.locationString") != null) {      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].laureateIfOrg.headquarters.locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].laureateIfOrg.headquarters.locationString.false"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].wikipedia") != null) {      
              if (response.get("laureates["+ i +"].wikipedia.slug") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].wikipedia.slug"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].wikipedia.english") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].wikipedia.english"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].wikidata") != null) {      
              if (response.get("laureates["+ i +"].wikidata.id") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].wikidata.id"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].wikidata.url") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].wikidata.url"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].sameAs") != null) {      
                for (int i1 = 0; i1 < response.getList("laureates["+ i +"].sameAs").size(); i1++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].sameAs"), instanceOf(List.class));
  
          }
      
              if (response.get("laureates["+ i +"].links") != null) {        
                  for (int i1 = 0; i1 < response.getList("laureates["+ i +"].links").size(); i1++) {      
              if (response.get("laureates["+ i +"].links["+ i1 +"].rel") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].links["+ i1 +"].rel"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].links["+ i1 +"].href") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].links["+ i1 +"].href"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].links["+ i1 +"].action") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].links["+ i1 +"].action"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].links["+ i1 +"].types") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].links["+ i1 +"].types"), instanceOf(String.class));  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].links"), instanceOf(List.class));
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes") != null) {        
                  for (int i1 = 0; i1 < response.getList("laureates["+ i +"].nobelPrizes").size(); i1++) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].awardYear") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].awardYear"), instanceOf(Integer.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].category") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].category.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].category.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].category.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].category.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].category.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].category.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].categoryFullName") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].categoryFullName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].categoryFullName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].categoryFullName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].categoryFullName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].categoryFullName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].categoryFullName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].sortOrder") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].sortOrder"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("laureates["+ i +"].nobelPrizes["+ i1 +"].sortOrder"), anyOf(equalTo("1"), equalTo("2"), equalTo("3")));
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].portion") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].portion"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("laureates["+ i +"].nobelPrizes["+ i1 +"].portion"), anyOf(equalTo("1"), equalTo("1/2"), equalTo("1/3"), equalTo("1/4")));
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].dateAwarded") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].dateAwarded"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].prizeStatus") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].prizeStatus"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("laureates["+ i +"].nobelPrizes["+ i1 +"].prizeStatus"), anyOf(equalTo("received"), equalTo("declined"), equalTo("restricted")));
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].motivation") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].motivation.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].motivation.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].motivation.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].motivation.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].motivation.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].motivation.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].prizeAmount") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].prizeAmount"), instanceOf(Integer.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].prizeAmountAdjusted") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].prizeAmountAdjusted"), instanceOf(Integer.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations") != null) {        
                  for (int i11 = 0; i11 < response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations").size(); i11++) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].name") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].name.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].name.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].name.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].name.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].name.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].name.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].nameNow") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].nameNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].nameNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].nameNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].nameNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].nameNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].nameNow.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].nativeName") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].nativeName"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].city") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].country") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].cityNow") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].cityNow.sameAs") != null) {      
                for (int i111 = 0; i111 < response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].cityNow.sameAs").size(); i111++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].countryNow") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].countryNow.sameAs") != null) {      
                for (int i111 = 0; i111 < response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].countryNow.sameAs").size(); i111++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].locationString") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations["+ i11 +"].locationString.false"), instanceOf(String.class));  
          }
  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].affiliations"), instanceOf(List.class));
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences") != null) {        
                  for (int i11 = 0; i11 < response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].residences").size(); i11++) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].city") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].country") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].cityNow") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].cityNow.sameAs") != null) {      
                for (int i111 = 0; i111 < response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].cityNow.sameAs").size(); i111++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].countryNow") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].countryNow.sameAs") != null) {      
                for (int i111 = 0; i111 < response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].countryNow.sameAs").size(); i111++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].locationString") != null) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].residences["+ i11 +"].locationString.false"), instanceOf(String.class));  
          }
  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].residences"), instanceOf(List.class));
  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].links") != null) {        
                  for (int i11 = 0; i11 < response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].links").size(); i11++) {      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].links["+ i11 +"].rel") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].links["+ i11 +"].rel"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].links["+ i11 +"].href") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].links["+ i11 +"].href"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].links["+ i11 +"].action") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].links["+ i11 +"].action"), instanceOf(String.class));  
          }
      
              if (response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].links["+ i11 +"].types") != null) {  
                MatcherAssert.assertThat(response.get("laureates["+ i +"].nobelPrizes["+ i1 +"].links["+ i11 +"].types"), instanceOf(String.class));  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].nobelPrizes["+ i1 +"].links"), instanceOf(List.class));
  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureates["+ i +"].nobelPrizes"), instanceOf(List.class));
  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureates"), instanceOf(List.class));
  
          }
      
              if (response.get("meta") != null) {      
              if (response.get("meta.offset") != null) {  
                MatcherAssert.assertThat(response.get("meta.offset"), instanceOf(Integer.class));  
          }
      
              if (response.get("meta.limit") != null) {  
                MatcherAssert.assertThat(response.get("meta.limit"), instanceOf(Integer.class));  
          }
      
              if (response.get("meta.sort") != null) {  
                MatcherAssert.assertThat(response.get("meta.sort"), instanceOf(String.class));  
          }
      
              if (response.get("meta.ID") != null) {  
                MatcherAssert.assertThat(response.get("meta.ID"), instanceOf(Integer.class));  
          }
      
              if (response.get("meta.name") != null) {  
                MatcherAssert.assertThat(response.get("meta.name"), instanceOf(String.class));  
          }
      
              if (response.get("meta.gender") != null) {  
                MatcherAssert.assertThat(response.get("meta.gender"), instanceOf(String.class));  
          }
      
              if (response.get("meta.motivation") != null) {  
                MatcherAssert.assertThat(response.get("meta.motivation"), instanceOf(String.class));  
          }
      
              if (response.get("meta.affiliation") != null) {  
                MatcherAssert.assertThat(response.get("meta.affiliation"), instanceOf(String.class));  
          }
      
              if (response.get("meta.residence") != null) {  
                MatcherAssert.assertThat(response.get("meta.residence"), instanceOf(String.class));  
          }
      
              if (response.get("meta.birthDate") != null) {  
                MatcherAssert.assertThat(response.get("meta.birthDate"), instanceOf(String.class));  
          }
      
              if (response.get("meta.birthDateTo") != null) {  
                MatcherAssert.assertThat(response.get("meta.birthDateTo"), instanceOf(String.class));  
          }
      
              if (response.get("meta.deathDate") != null) {  
                MatcherAssert.assertThat(response.get("meta.deathDate"), instanceOf(String.class));  
          }
      
              if (response.get("meta.deathDateTo") != null) {  
                MatcherAssert.assertThat(response.get("meta.deathDateTo"), instanceOf(String.class));  
          }
      
              if (response.get("meta.foundedDate") != null) {  
                MatcherAssert.assertThat(response.get("meta.foundedDate"), instanceOf(String.class));  
          }
      
              if (response.get("meta.birthCity") != null) {  
                MatcherAssert.assertThat(response.get("meta.birthCity"), instanceOf(String.class));  
          }
      
              if (response.get("meta.birthCountry") != null) {  
                MatcherAssert.assertThat(response.get("meta.birthCountry"), instanceOf(String.class));  
          }
      
              if (response.get("meta.birthContinent") != null) {  
                MatcherAssert.assertThat(response.get("meta.birthContinent"), instanceOf(String.class));  
          }
      
              if (response.get("meta.deathCity") != null) {  
                MatcherAssert.assertThat(response.get("meta.deathCity"), instanceOf(String.class));  
          }
      
              if (response.get("meta.deathCountry") != null) {  
                MatcherAssert.assertThat(response.get("meta.deathCountry"), instanceOf(String.class));  
          }
      
              if (response.get("meta.deathContinent") != null) {  
                MatcherAssert.assertThat(response.get("meta.deathContinent"), instanceOf(String.class));  
          }
      
              if (response.get("meta.foundedCity") != null) {  
                MatcherAssert.assertThat(response.get("meta.foundedCity"), instanceOf(String.class));  
          }
      
              if (response.get("meta.foundedCountry") != null) {  
                MatcherAssert.assertThat(response.get("meta.foundedCountry"), instanceOf(String.class));  
          }
      
              if (response.get("meta.foundedContinent") != null) {  
                MatcherAssert.assertThat(response.get("meta.foundedContinent"), instanceOf(String.class));  
          }
      
              if (response.get("meta.headquartersCity") != null) {  
                MatcherAssert.assertThat(response.get("meta.headquartersCity"), instanceOf(String.class));  
          }
      
              if (response.get("meta.headquartersCountry") != null) {  
                MatcherAssert.assertThat(response.get("meta.headquartersCountry"), instanceOf(String.class));  
          }
      
              if (response.get("meta.headquartersContinent") != null) {  
                MatcherAssert.assertThat(response.get("meta.headquartersContinent"), instanceOf(String.class));  
          }
      
              if (response.get("meta.nobelPrizeYear") != null) {  
                MatcherAssert.assertThat(response.get("meta.nobelPrizeYear"), instanceOf(Integer.class));  
          }
      
              if (response.get("meta.yearTo") != null) {  
                MatcherAssert.assertThat(response.get("meta.yearTo"), instanceOf(Integer.class));  
          }
      
              if (response.get("meta.nobelPrizeCategory") != null) {  
                MatcherAssert.assertThat(response.get("meta.nobelPrizeCategory"), instanceOf(String.class));  
          }
      
              if (response.get("meta.count") != null) {  
                MatcherAssert.assertThat(response.get("meta.count"), instanceOf(Integer.class));  
          }
  
          }
      
              if (response.get("links") != null) {        
                  for (int i = 0; i < response.getList("links").size(); i++) {      
              if (response.get("links["+ i +"].first") != null) {  
                MatcherAssert.assertThat(response.get("links["+ i +"].first"), instanceOf(String.class));  
          }
      
              if (response.get("links["+ i +"].prev") != null) {  
                MatcherAssert.assertThat(response.get("links["+ i +"].prev"), instanceOf(String.class));  
          }
      
              if (response.get("links["+ i +"].self") != null) {  
                MatcherAssert.assertThat(response.get("links["+ i +"].self"), instanceOf(String.class));  
          }
      
              if (response.get("links["+ i +"].next") != null) {  
                MatcherAssert.assertThat(response.get("links["+ i +"].next"), instanceOf(String.class));  
          }
      
              if (response.get("links["+ i +"].last") != null) {  
                MatcherAssert.assertThat(response.get("links["+ i +"].last"), instanceOf(String.class));  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("links"), instanceOf(List.class));
  
          }
				}
if (responseObj.statusCode() == 400) {
					System.out.println("Description: Bad request.The request could not be understood by the server due to malformed syntax, modifications needed.");
      
              if (response.get("code") != null) {  
                MatcherAssert.assertThat(response.get("code"), instanceOf(String.class));  
          }
      
              if (response.get("message") != null) {  
                MatcherAssert.assertThat(response.get("message"), instanceOf(String.class));  
          }
				}
if (responseObj.statusCode() == 404) {
					System.out.println("Description: Not Found. The requested resource could not be found but may be available again in the future.");
      
              if (response.get("code") != null) {  
                MatcherAssert.assertThat(response.get("code"), instanceOf(String.class));  
          }
      
              if (response.get("message") != null) {  
                MatcherAssert.assertThat(response.get("message"), instanceOf(String.class));  
          }
				}
if (responseObj.statusCode() == 422) {
					System.out.println("Description: Unprocessable Entity. The request was well-formed but was unable to be followed due to semantic errors.");
      
              if (response.get("code") != null) {  
                MatcherAssert.assertThat(response.get("code"), instanceOf(String.class));  
          }
      
              if (response.get("message") != null) {  
                MatcherAssert.assertThat(response.get("message"), instanceOf(String.class));  
          }
				}
  
            }  
    }
}
