// ********RoostGPT********
/*
Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview

Test generated for /laureate/{laureateID}_get for http method type GET in rest-assured framework

RoostTestHash=3a8d014c99


*/

// ********RoostGPT********
package com.baeldung.RoostTest;
import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import org.json.JSONArray;

public class laureateLaureateIdGetTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      String[] envVarsList = {"laureateID"};
      envList = dataloader.load("src\test\java\com\baeldung\RoostTest\laureate_laureateIDGetTest.csv", envVarsList);
    }

  
    @Test  
    public void laureateLaureateIdGet_Test() {
        this.setUp();
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty()) ? testData.get("BASE_URL"): "http://api.nobelprize.org/2.1";  
  
                Response responseObj = given()
				.pathParam("laureateID", testData.get("laureateID") != null ? testData.get("laureateID") : "")
                .when()
                .get("/laureate/{laureateID}")  
                .then() 
                .extract().response(); 
              JsonPath response;
              String contentType = responseObj.getContentType();
              if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
                String xmlResponse = responseObj.asString();
                JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
                JSONObject jsonData = jsonResponse.getJSONObject("xml");
                String jsonString = jsonData.toString();
                response = new JsonPath(jsonString);
        
              } else {  
                response = responseObj.jsonPath(); 
              }  
         
                if (responseObj.statusCode() == 200) {
					System.out.println("Description: Successful call of Laureate given the ID");
      
              if (response.get("laureate") != null) {      
              if (response.get("laureate.id") != null) {  
                MatcherAssert.assertThat(response.get("laureate.id"), instanceOf(Integer.class));  
                MatcherAssert.assertThat(response.getDouble("laureate.id"), greaterThanOrEqualTo(1));
  
          }
      
              if (response.get("laureate.laureateIfPerson") != null) {      
              if (response.get("laureate.laureateIfPerson.knownName") != null) {      
              if (response.get("laureate.laureateIfPerson.knownName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.knownName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.knownName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.knownName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.knownName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.knownName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.givenName") != null) {      
              if (response.get("laureate.laureateIfPerson.givenName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.givenName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.givenName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.givenName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.givenName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.givenName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.familyName") != null) {      
              if (response.get("laureate.laureateIfPerson.familyName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.familyName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.familyName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.familyName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.familyName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.familyName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.fullName") != null) {      
              if (response.get("laureate.laureateIfPerson.fullName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.fullName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.fullName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.fullName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.fullName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.fullName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.filename") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.filename"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.penname") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.penname"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.gender") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.gender"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("laureate.laureateIfPerson.gender"), anyOf(equalTo("female"), equalTo("male")));
  
          }
      
              if (response.get("laureate.laureateIfPerson.birth") != null) {      
              if (response.get("laureate.laureateIfPerson.birth.date") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.date"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place") != null) {      
              if (response.get("laureate.laureateIfPerson.birth.place.city") != null) {      
              if (response.get("laureate.laureateIfPerson.birth.place.city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.country") != null) {      
              if (response.get("laureate.laureateIfPerson.birth.place.country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.cityNow") != null) {      
              if (response.get("laureate.laureateIfPerson.birth.place.cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.cityNow.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.laureateIfPerson.birth.place.cityNow.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.laureateIfPerson.birth.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.countryNow") != null) {      
              if (response.get("laureate.laureateIfPerson.birth.place.countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.countryNow.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.laureateIfPerson.birth.place.countryNow.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.laureateIfPerson.birth.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.continent") != null) {      
              if (response.get("laureate.laureateIfPerson.birth.place.continent.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.continent.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.continent.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.continent.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.continent.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.continent.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.locationString") != null) {      
              if (response.get("laureate.laureateIfPerson.birth.place.locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.birth.place.locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.birth.place.locationString.false"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.death") != null) {      
              if (response.get("laureate.laureateIfPerson.death.date") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.date"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place") != null) {      
              if (response.get("laureate.laureateIfPerson.death.place.city") != null) {      
              if (response.get("laureate.laureateIfPerson.death.place.city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.country") != null) {      
              if (response.get("laureate.laureateIfPerson.death.place.country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.cityNow") != null) {      
              if (response.get("laureate.laureateIfPerson.death.place.cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.cityNow.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.laureateIfPerson.death.place.cityNow.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.laureateIfPerson.death.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.countryNow") != null) {      
              if (response.get("laureate.laureateIfPerson.death.place.countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.countryNow.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.laureateIfPerson.death.place.countryNow.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.laureateIfPerson.death.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.continent") != null) {      
              if (response.get("laureate.laureateIfPerson.death.place.continent.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.continent.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.continent.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.continent.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.continent.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.continent.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.locationString") != null) {      
              if (response.get("laureate.laureateIfPerson.death.place.locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfPerson.death.place.locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfPerson.death.place.locationString.false"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg") != null) {      
              if (response.get("laureate.laureateIfOrg.orgName") != null) {      
              if (response.get("laureate.laureateIfOrg.orgName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.orgName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.orgName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.orgName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.orgName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.orgName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.nativeName") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.nativeName"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.acronym") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.acronym"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded") != null) {      
              if (response.get("laureate.laureateIfOrg.founded.date") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.date"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place") != null) {      
              if (response.get("laureate.laureateIfOrg.founded.place.city") != null) {      
              if (response.get("laureate.laureateIfOrg.founded.place.city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.country") != null) {      
              if (response.get("laureate.laureateIfOrg.founded.place.country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.cityNow") != null) {      
              if (response.get("laureate.laureateIfOrg.founded.place.cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.cityNow.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.laureateIfOrg.founded.place.cityNow.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.laureateIfOrg.founded.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.countryNow") != null) {      
              if (response.get("laureate.laureateIfOrg.founded.place.countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.countryNow.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.laureateIfOrg.founded.place.countryNow.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.laureateIfOrg.founded.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.continent") != null) {      
              if (response.get("laureate.laureateIfOrg.founded.place.continent.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.continent.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.continent.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.continent.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.continent.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.continent.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.locationString") != null) {      
              if (response.get("laureate.laureateIfOrg.founded.place.locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.founded.place.locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.founded.place.locationString.false"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution") != null) {      
              if (response.get("laureate.laureateIfOrg.dissolution.date") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.date"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place") != null) {      
              if (response.get("laureate.laureateIfOrg.dissolution.place.city") != null) {      
              if (response.get("laureate.laureateIfOrg.dissolution.place.city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.country") != null) {      
              if (response.get("laureate.laureateIfOrg.dissolution.place.country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.cityNow") != null) {      
              if (response.get("laureate.laureateIfOrg.dissolution.place.cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.cityNow.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.laureateIfOrg.dissolution.place.cityNow.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.laureateIfOrg.dissolution.place.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.countryNow") != null) {      
              if (response.get("laureate.laureateIfOrg.dissolution.place.countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.countryNow.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.laureateIfOrg.dissolution.place.countryNow.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.laureateIfOrg.dissolution.place.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.continent") != null) {      
              if (response.get("laureate.laureateIfOrg.dissolution.place.continent.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.continent.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.continent.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.continent.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.continent.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.continent.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.locationString") != null) {      
              if (response.get("laureate.laureateIfOrg.dissolution.place.locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.dissolution.place.locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.dissolution.place.locationString.false"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters") != null) {      
              if (response.get("laureate.laureateIfOrg.headquarters.city") != null) {      
              if (response.get("laureate.laureateIfOrg.headquarters.city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.country") != null) {      
              if (response.get("laureate.laureateIfOrg.headquarters.country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.cityNow") != null) {      
              if (response.get("laureate.laureateIfOrg.headquarters.cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.cityNow.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.laureateIfOrg.headquarters.cityNow.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.laureateIfOrg.headquarters.cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.countryNow") != null) {      
              if (response.get("laureate.laureateIfOrg.headquarters.countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.countryNow.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.laureateIfOrg.headquarters.countryNow.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.laureateIfOrg.headquarters.countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.continent") != null) {      
              if (response.get("laureate.laureateIfOrg.headquarters.continent.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.continent.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.continent.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.continent.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.continent.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.continent.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.locationString") != null) {      
              if (response.get("laureate.laureateIfOrg.headquarters.locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.laureateIfOrg.headquarters.locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.laureateIfOrg.headquarters.locationString.false"), instanceOf(String.class));  
          }
  
          }
  
          }
  
          }
      
              if (response.get("laureate.wikipedia") != null) {      
              if (response.get("laureate.wikipedia.slug") != null) {  
                MatcherAssert.assertThat(response.get("laureate.wikipedia.slug"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.wikipedia.english") != null) {  
                MatcherAssert.assertThat(response.get("laureate.wikipedia.english"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.wikidata") != null) {      
              if (response.get("laureate.wikidata.id") != null) {  
                MatcherAssert.assertThat(response.get("laureate.wikidata.id"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.wikidata.url") != null) {  
                MatcherAssert.assertThat(response.get("laureate.wikidata.url"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.sameAs") != null) {      
                for (int i = 0; i < response.getList("laureate.sameAs").size(); i++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.sameAs"), instanceOf(List.class));
  
          }
      
              if (response.get("laureate.links") != null) {        
                  for (int i = 0; i < response.getList("laureate.links").size(); i++) {      
              if (response.get("laureate.links["+ i +"].rel") != null) {  
                MatcherAssert.assertThat(response.get("laureate.links["+ i +"].rel"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.links["+ i +"].href") != null) {  
                MatcherAssert.assertThat(response.get("laureate.links["+ i +"].href"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.links["+ i +"].action") != null) {  
                MatcherAssert.assertThat(response.get("laureate.links["+ i +"].action"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.links["+ i +"].types") != null) {  
                MatcherAssert.assertThat(response.get("laureate.links["+ i +"].types"), instanceOf(String.class));  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureate.links"), instanceOf(List.class));
  
          }
      
              if (response.get("laureate.nobelPrizes") != null) {        
                  for (int i = 0; i < response.getList("laureate.nobelPrizes").size(); i++) {      
              if (response.get("laureate.nobelPrizes["+ i +"].awardYear") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].awardYear"), instanceOf(Integer.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].category") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].category.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].category.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].category.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].category.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].category.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].category.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].categoryFullName") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].categoryFullName.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].categoryFullName.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].categoryFullName.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].categoryFullName.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].categoryFullName.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].categoryFullName.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].sortOrder") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].sortOrder"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("laureate.nobelPrizes["+ i +"].sortOrder"), anyOf(equalTo("1"), equalTo("2"), equalTo("3")));
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].portion") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].portion"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("laureate.nobelPrizes["+ i +"].portion"), anyOf(equalTo("1"), equalTo("1/2"), equalTo("1/3"), equalTo("1/4")));
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].dateAwarded") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].dateAwarded"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].prizeStatus") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].prizeStatus"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("laureate.nobelPrizes["+ i +"].prizeStatus"), anyOf(equalTo("received"), equalTo("declined"), equalTo("restricted")));
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].motivation") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].motivation.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].motivation.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].motivation.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].motivation.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].motivation.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].motivation.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].prizeAmount") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].prizeAmount"), instanceOf(Integer.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].prizeAmountAdjusted") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].prizeAmountAdjusted"), instanceOf(Integer.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations") != null) {        
                  for (int i1 = 0; i1 < response.getList("laureate.nobelPrizes["+ i +"].affiliations").size(); i1++) {      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].name") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].name.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].name.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].name.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].name.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].name.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].name.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].nameNow") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].nameNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].nameNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].nameNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].nameNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].nameNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].nameNow.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].nativeName") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].nativeName"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].city") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].country") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].cityNow") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].cityNow.sameAs") != null) {      
                for (int i11 = 0; i11 < response.getList("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].cityNow.sameAs").size(); i11++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].countryNow") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].countryNow.sameAs") != null) {      
                for (int i11 = 0; i11 < response.getList("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].countryNow.sameAs").size(); i11++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].locationString") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].affiliations["+ i1 +"].locationString.false"), instanceOf(String.class));  
          }
  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureate.nobelPrizes["+ i +"].affiliations"), instanceOf(List.class));
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences") != null) {        
                  for (int i1 = 0; i1 < response.getList("laureate.nobelPrizes["+ i +"].residences").size(); i1++) {      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].city") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].city.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].city.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].city.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].city.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].city.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].city.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].country") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].country.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].country.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].country.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].country.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].country.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].country.false"), instanceOf(String.class));  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].cityNow") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].cityNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].cityNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].cityNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].cityNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].cityNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].cityNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].cityNow.sameAs") != null) {      
                for (int i11 = 0; i11 < response.getList("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].cityNow.sameAs").size(); i11++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].cityNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].countryNow") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].countryNow.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].countryNow.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].countryNow.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].countryNow.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].countryNow.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].countryNow.false"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].countryNow.sameAs") != null) {      
                for (int i11 = 0; i11 < response.getList("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].countryNow.sameAs").size(); i11++) {      
                  }    
                MatcherAssert.assertThat(response.getList("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].countryNow.sameAs"), instanceOf(List.class));
  
          }
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].locationString") != null) {      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].locationString.en") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].locationString.en"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].locationString.se") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].locationString.se"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].locationString.false") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].residences["+ i1 +"].locationString.false"), instanceOf(String.class));  
          }
  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureate.nobelPrizes["+ i +"].residences"), instanceOf(List.class));
  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].links") != null) {        
                  for (int i1 = 0; i1 < response.getList("laureate.nobelPrizes["+ i +"].links").size(); i1++) {      
              if (response.get("laureate.nobelPrizes["+ i +"].links["+ i1 +"].rel") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].links["+ i1 +"].rel"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].links["+ i1 +"].href") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].links["+ i1 +"].href"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].links["+ i1 +"].action") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].links["+ i1 +"].action"), instanceOf(String.class));  
          }
      
              if (response.get("laureate.nobelPrizes["+ i +"].links["+ i1 +"].types") != null) {  
                MatcherAssert.assertThat(response.get("laureate.nobelPrizes["+ i +"].links["+ i1 +"].types"), instanceOf(String.class));  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureate.nobelPrizes["+ i +"].links"), instanceOf(List.class));
  
          }
        
                    }    
                MatcherAssert.assertThat(response.getList("laureate.nobelPrizes"), instanceOf(List.class));
  
          }
  
          }
				}
if (responseObj.statusCode() == 400) {
					System.out.println("Description: Bad request.The request could not be understood by the server due to malformed syntax, modifications needed.");
      
              if (response.get("code") != null) {  
                MatcherAssert.assertThat(response.get("code"), instanceOf(String.class));  
          }
      
              if (response.get("message") != null) {  
                MatcherAssert.assertThat(response.get("message"), instanceOf(String.class));  
          }
				}
if (responseObj.statusCode() == 404) {
					System.out.println("Description: Not Found. The requested resource could not be found but may be available again in the future.");
      
              if (response.get("code") != null) {  
                MatcherAssert.assertThat(response.get("code"), instanceOf(String.class));  
          }
      
              if (response.get("message") != null) {  
                MatcherAssert.assertThat(response.get("message"), instanceOf(String.class));  
          }
				}
if (responseObj.statusCode() == 422) {
					System.out.println("Description: Unprocessable Entity. The request was well-formed but was unable to be followed due to semantic errors.");
      
              if (response.get("code") != null) {  
                MatcherAssert.assertThat(response.get("code"), instanceOf(String.class));  
          }
      
              if (response.get("message") != null) {  
                MatcherAssert.assertThat(response.get("message"), instanceOf(String.class));  
          }
				}
  
            }  
    }
}
